name: lichee
description: Lichee Flutter App.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.0.0
  cloud_firestore: ^3.1.1
  firebase_storage: ^10.2.0
  firebase_auth: ^3.3.0
  firebase_core: ^1.10.2
  provider: ^6.0.1
  fluttertoast: ^8.0.8
  modal_progress_hud_nsn: ^0.1.0-nullsafety-0
  datetime_picker_formfield: ^2.0.0
  intl: ^0.17.0
  rxdart: ^0.27.3
  filter_list: ^1.0.0
  image_picker: ^0.8.4+4
  smooth_page_indicator: ^1.0.0+2
  diacritic: ^0.1.3

  # tests
  mockito: ^5.0.16
  fake_cloud_firestore: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
